name: npm-publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v1
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn global add pnpm
      - run: pnpm install
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/react-device-frameset/package.json
          dry-run: true